return {
	["Drills"] = {
		["Main"] = {
			["Rusty"] = 0,
			["Steel"] = 100,
			["Golden"] = 1000,
			["Candy"] = 25000,
			["Neon"] = 150000,
			["Cyber"] = 3500000,
			["Diamond"] = 50000000,
			["Lava"] = 250000000,
			["Infinity"] = 1000000000,
			["Quantum"] = 1100000000,
		},
		["Dinosaur"] = {
			["Fossil"] = 2e9,
			["Volcano"] = 15000000000,
			["Amber"] = 50000000000,
			["Crusher"] = 5500000000,
		},
		["Frozen"] = {
			["Glacier"] = 5e11,
			["Icebreaker"] = 1.5e12,
			["Permafrost"] = 5e12,
			["Maelstrom"] = 5.5e12,
		},
		["Jungle"] = {
			["Vinecutter"] = 1e13,
			["Jungle Beast"] = 2.5e13,
			["Thornspike"] = 5e13,
			["Ravager"] = 6e13,
		},
		["Magic"] = {
			["Spellboun"] = 500e12,
			["Arcane Auger"] = 25e15,
			["Mystic Bore"] = 100e15,
		},
	},
	["Eggs"] = {
		["Main"] = {
			["Beach Egg"] = 100,
			["Oceanic Egg"] = 100000,
			["Lava Egg"] = 10000000,
		},
		["Dinosaur"] = {
			["Fossil Egg"] = 100000000,
			["Jurassic Egg"] = 1e9,
		},
		["Frozen"] = {
			["Glacier Egg"] = 1e11,
			["Blizzard Egg"] = 1e12,
		},
		["Jungle"] = {
			["Tropical Egg"] = 2e12,
			["Jungle Egg"] = 1e13,
		},
		["Magic"] = {
			["Ember Egg"] = 250e12,
			["Enigma Egg"] = 2.5e15,
			["Necromancer Egg"] = 1,
		},
	},
	["Pets"] = {
		["Beach Egg"] = {
			["Sand Golem"] = "Epic",
			["Crab"] = "Common",
			["Monkey"] = "Uncommon",
			["Seagull"] = "Uncommon",
			["Parrot"] = "Uncommon",
		},
		["Without Egg"] = {
			["Cyber Megalodon"] = "Exclusive",
			["Solar Pheonix"] = "Exclusive",
			["Inferno Rex"] = "Exclusive",
			["Frostbite Leviathan"] = "Exclusive",
			["Jungle King"] = "Exclusive",
			["Obscure Oracle"] = "Exclusive",
		},
		["Lava Egg"] = {
			["Pheonix"] = "Epic",
			["Magma Dragon"] = "Legendary",
			["Fire Ant"] = "Uncommon",
			["Molten Crab"] = "Uncommon",
			["Lava Turtle"] = "Uncommon",
			["Pearl Phantom"] = "Mythic",
		},
		["Oceanic Egg"] = {
			["Stingray"] = "Rare",
			["Clownfish"] = "Common",
			["Electric Eel"] = "Uncommon",
			["Starfish"] = "Common",
			["Megalodon"] = "Epic",
			["Coral Sentinel"] = "Legendary",
		},
		["Fossil Egg"] = {
			["Raptor"] = "Common",
			["Triceratops"] = "Uncommon",
			["Stegosaurus"] = "Uncommon",
			["Parasaur"] = "Rare",
			["Shadow Rex"] = "Epic",
			["Bronto"] = "Legendary",
			["Fossilized Fury"] = "Mythic",
		},
		["Jurassic Egg"] = {
			["Dodo Chick"] = "Common",
			["Pangolin"] = "Uncommon",
			["Sabertooth"] = "Uncommon",
			["Plesiosaur"] = "Rare",
			["Ankylosaur"] = "Epic",
			["Ghost Spino"] = "Legendary",
			["Primal Shade"] = "Mythic",
		},
		["Glacier Egg"] = {
			["Snowy Hare"] = "Common",
			["Chipmunk"] = "Common",
			["Artic Fox"] = "Uncommon",
			["Penguin"] = "Rare",
			["Frozen Wolf"] = "Epic",
			["Aurora Lynx"] = "Legendary",
			["Glaciar Specter"] = "Mythic",
		},
		["Blizzard Egg"] = {
			["Elk"] = "Uncommon",
			["Ice Mole"] = "Common",
			["Aurora Sprite"] = "Exclusive",
			["Storm Serpent"] = "Epic",
			["Mammoth"] = "Legendary",
			["Polar Bear"] = "Rare",
			["Snowy Owl"] = "Common",
		},
		["Jungle Egg"] = {
			["Jaguar"] = "Common",
			["Red Parrot"] = "Uncommon",
			["Panther"] = "Rare",
			["Tiger"] = "Epic",
			["Gorilla"] = "Legendary",
		},
		["Tropical Egg"] = {
			["Leafhopper"] = "Common",
			["Bramble Rat"] = "Common",
			["Gecko"] = "Uncommon",
			["Thorn Turtle"] = "Rare",
			["Scorpion"] = "Epic",
			["Viper"] = "Legendary",
		},
		["Necromancer Egg"] = {
			["Revenant"] = "Common",
			["Forsaken Phantom"] = "Rare",
			["Blighted Wraith"] = "Common",
			["Necro Shade"] = "Legendary",
			["Cursed Banshee"] = "Exclusive",
		},
		["Enigma Egg"] = {
			["Misty Moppet"] = "Common",
			["Fae Fluff"] = "Common",
			["Shimmer Sprite"] = "Uncommon",
			["Radiant Raven"] = "Rare",
			["Magus Manticore"] = "Epic",
			["Arcane Archon"] = "Legendary",
		},
		["Ember Egg"] = {
			["Sparkle Sprout"] = "Common",
			["Twinkle Tot"] = "Common",
			["Gremlin"] = "Uncommon",
			["Chimera"] = "Legendary",
			["Aurora Aesthercat"] = "Rare",
			["Ethereal Elf"] = "Epic",
		},
	},
	["PetRarity"] = {
		["Sand Golem"] = "Epic",
		["Crab"] = "Common",
		["Monkey"] = "Uncommon",
		["Seagull"] = "Uncommon",
		["Parrot"] = "Uncommon",
		["Cyber Megalodon"] = "Exclusive",
		["Solar Pheonix"] = "Exclusive",
		["Inferno Rex"] = "Exclusive",
		["Frostbite Leviathan"] = "Exclusive",
		["Jungle King"] = "Exclusive",
		["Obscure Oracle"] = "Exclusive",
		["Pheonix"] = "Epic",
		["Magma Dragon"] = "Legendary",
		["Fire Ant"] = "Uncommon",
		["Molten Crab"] = "Uncommon",
		["Lava Turtle"] = "Uncommon",
		["Pearl Phantom"] = "Mythic",
		["Stingray"] = "Rare",
		["Clownfish"] = "Common",
		["Electric Eel"] = "Uncommon",
		["Starfish"] = "Common",
		["Megalodon"] = "Epic",
		["Coral Sentinel"] = "Legendary",
		["Raptor"] = "Common",
		["Triceratops"] = "Uncommon",
		["Stegosaurus"] = "Uncommon",
		["Parasaur"] = "Rare",
		["Shadow Rex"] = "Epic",
		["Bronto"] = "Legendary",
		["Fossilized Fury"] = "Mythic",
		["Dodo Chick"] = "Common",
		["Pangolin"] = "Uncommon",
		["Sabertooth"] = "Uncommon",
		["Plesiosaur"] = "Rare",
		["Ankylosaur"] = "Epic",
		["Ghost Spino"] = "Legendary",
		["Primal Shade"] = "Mythic",
		["Leafhopper"] = "Common",
		["Bramble Rat"] = "Common",
		["Gecko"] = "Uncommon",
		["Thorn Turtle"] = "Rare",
		["Scorpion"] = "Epic",
		["Viper"] = "Legendary",
		["Revenant"] = "Common",
		["Forsaken Phantom"] = "Rare",
		["Blighted Wraith"] = "Common",
		["Necro Shade"] = "Legendary",
		["Cursed Banshee"] = "Exclusive",
		["Misty Moppet"] = "Common",
		["Fae Fluff"] = "Common",
		["Shimmer Sprite"] = "Uncommon",
		["Radiant Raven"] = "Rare",
		["Magus Manticore"] = "Epic",
		["Arcane Archon"] = "Legendary",
		["Sparkle Sprout"] = "Common",
		["Twinkle Tot"] = "Common",
		["Gremlin"] = "Uncommon",
		["Chimera"] = "Legendary",
		["Aurora Aesthercat"] = "Rare",
		["Ethereal Elf"] = "Epic",
	},
}
