return {
  CropRarities = {
			["Carrot Seed"] = "Common",
			["Strawberry Seed"] = "Common",
			["Blueberry Seed"] = "Uncommon",
			["Orange Tulip"] = "Uncommon",
			["Tomato Seed"] = "Rare",
			["Corn Seed"] = "Rare",
			["Daffodil Seed"] = "Legendary",
			["Watermelon Seed"] = "Legendary",
			["Pumpkin Seed"] = "Legendary",
			["Apple Seed"] = "Legendary",
      ["Bamboo Seed"] = "Legendary",
			["Coconut Seed"] = "Mythical",
			["Cactus Seed"] = "Mythical",
			["Dragon Fruit Seed"] = "Mythical",
			["Mango Seed"] = "Mythical",
			["Grape Seed"] = "Divine",
		},
  Crops = {
			"Carrot Seed",
			"Strawberry Seed",
			"Blueberry Seed",
			"Orange Tulip",
			"Tomato Seed",
			"Corn Seed",
			"Daffodil Seed",
			"Watermelon Seed",
			"Pumpkin Seed",
			"Apple Seed",
      "Bamboo Seed",
			"Coconut Seed",
			"Cactus Seed",
			"Dragon Fruit Seed",
			"Mango Seed",
			"Grape Seed",
		}
}
